apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lzlkcsh9i-python 
  janus-idp.io/tekton: lzlkcsh9i-python
  backstage.io/kubernetes-id: lzlkcsh9i-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lzlkcsh9i-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml