apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lzlkcsh9i-python
  janus-idp.io/tekton: lzlkcsh9i-python
  backstage.io/kubernetes-id: lzlkcsh9i-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lzlkcsh9i-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
